name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.3
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      pnpm-version: 8.5.1
      node-version: 18.16.0
      number-of-agents: 3
      main-branch-name: 'develop'
      init-commands: |
        pnpm nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands-on-agents: |
        pnpm nx affected --target=lint --parallel=3
        pnpm nx affected --target=test:ci --parallel=3
        pnpm nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.3
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      number-of-agents: 3
      pnpm-version: 8.5.1
      node-version: 18.16.0
