name: Docs deploy/build action

on:
  pull_request:
    branches: [master, develop]
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/docs/**'
      - 'Dockerfile'
  push:
    branches: [master, develop]
    paths:
      - 'packages/docs/**'
      - 'Dockerfile'

jobs:
  test-build:
    # Test build on every PR to DEVELOP and MASTER
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'develop'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.30.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm nx run @blockchain-lab-um/masca-docs:lint
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - name: Test build docs
        run: pnpm nx run @blockchain-lab-um/masca-docs:build
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

  test-deploy:
    # Test deploy when we PUSH to DEVELOP
    if: ${{ (github.ref == 'refs/heads/develop') && (github.event_name == 'push') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create nx-cloud.env
        run: echo "NX_CLOUD_ACCESS_TOKEN=$NX_CLOUD_ACCESS_TOKEN" > nx-cloud.env
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - name: Build blockchain-lab-um/masca
        run: docker build . -t blockchain-lab-um/masca
      - name: Build blockchain-lab-um/masca-docs
        run: docker build ./packages/docs -t blockchain-lab-um/masca-docs
      - name: Change image tag
        run: docker tag blockchain-lab-um/masca-docs:latest bclabum.informatika.uni-mb.si/registry/masca-docs:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: bclabum.informatika.uni-mb.si/registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to private docker registry
        run: docker push bclabum.informatika.uni-mb.si/registry/masca-docs:latest

  deploy:
    # Deploy only when we PUSH to MASTER
    if: ${{ (github.ref == 'refs/heads/master') && (github.event_name == 'push') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.30.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: pnpm
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        run: |
          git config --global user.email "andraz.vrecko@gmail.com"
          git config --global user.name "andyv09"
          pnpm install --frozen-lockfile
          pnpm deploy:docs
