on:
  schedule:
    - cron: '15 14 * * *'

jobs:
  main:
    name: Nx Cloud - Cron Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      pnpm-version: 8.6.10
      node-version: 18.16.0
      number-of-agents: 2
      main-branch-name: 'tests/polygon-flow-tests'
      parallel-commands-on-agents: |
        pnpm exec nx run-many --target=lint --parallel=2
        pnpm exec nx run-many --target=test:cron --parallel=2
        pnpm exec nx run-many --target=build --parallel=2

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      number-of-agents: 2
      pnpm-version: 8.6.10
      node-version: 18.16.0
