name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.18.1
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'
          cache-depndency-path: '**/yarn.lock'
      - run: yarn install --immutable
      - run: yarn build
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        run: |
          echo npmAuthToken: "$NODE_AUTH_TOKEN" >> ./.yarnrc.yml
      - run: yarn workspaces foreach -v --exclude root --no-private npm publish --tolerate-republish --access public
