name: Sonarqube Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'develop'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.25.1
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm run test:ci
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - name: SonarQube Scan
        run: ./scripts/sonar/run-sonar.sh
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        timeout-minutes: 30

    services:
      sonarqube:
        image: sonarqube:8.9-community
        ports:
          - 9000:9000
