name: SonarCloud
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Snap
  sonarcloud-snap:
    name: SonarCloud snap
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'develop'
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.11.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm nx test:ci @blockchain-lab-um/masca
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - name: Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: packages/snap
          args: >
            -Dsonar.organization=blockchain-lab-um
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  # VC Manager
  sonarcloud-datamanager:
    name: SonarCloud datamanager
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'develop'
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.11.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm nx test:ci @blockchain-lab-um/veramo-datamanager
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - name: Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: packages/datamanager
          args: >
            -Dsonar.organization=blockchain-lab-um
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  # Connector
  sonarcloud-connector:
    name: SonarCloud connector
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: packages/connector
          args: >
            -Dsonar.organization=blockchain-lab-um
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  # Dapp
  sonarcloud-dapp:
    name: SonarCloud dapp
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: packages/dapp
          args: >
            -Dsonar.organization=blockchain-lab-um
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  # Docs
  sonarcloud-docs:
    name: SonarCloud docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: packages/docs
          args: >
            -Dsonar.organization=blockchain-lab-um
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  # Did-provider-key
  sonarcloud-did-provider-key:
    name: SonarCloud did-provider-key
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'develop'
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.11.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm nx test:ci @blockchain-lab-um/did-provider-key
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - name: Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: libs/did-provider-key
          args: >
            -Dsonar.organization=blockchain-lab-um
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
  # Did-provider-key
  sonarcloud-extended-verification-lib:
    name: SonarCloud extended-verification-lib
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'develop'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.11.0
      - uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm nx test:ci @blockchain-lab-um/extended-verification
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - name: Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: libs/extended-verification
          args: >
            -Dsonar.organization=blockchain-lab-um
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
